ITL-10 Create CRUD operations
Fekete-Balazs710/ToDo pull request #10
Opened 2023-08-11 06:51 UTC by Fekete-Balazs710

2023-08-16 08:12 UTC, SzaszWebgurus requested changes

2023-08-16 08:12 UTC, SzaszWebgurus commented on client/src/router/router.ts
> +        { path: "/", component: Login}
use redirect here

2023-08-16 08:12 UTC, SzaszWebgurus commented on client/src/service/todo.Delete.ts
merge all service micro files into a single todo-service.ts file, which exports a TodoService instance, with the service functions

2023-08-16 09:26 UTC, SzaszWebgurus requested changes

2023-08-16 09:26 UTC, SzaszWebgurus commented on server/service/todoService.js
> +    async updateIsEditing(req, res) {
this is only a temporary state, and shouldn't be saved in the database

2023-08-16 09:26 UTC, SzaszWebgurus commented on server/service/todoService.js
> +    async deleteTodo(req, res) {
just delete, don't need to name it like deleteTodo, because the context is given by the class name

2023-08-16 09:26 UTC, SzaszWebgurus commented on server/service/todoService.js
> +    async deleteTodo(req, res) {
the request and response object shouldn't be here, only in the controllers...here you need only the todoId as parameter...apply this logic to each service function

2023-08-16 09:26 UTC, SzaszWebgurus commented on server/service/todoService.js
> +    async updateIsChecked(req, res) {
a single generic update method is more than enough for now

2023-08-16 09:26 UTC, SzaszWebgurus commented on server/model/todosModel.js
> +    // userId: {
remove unused code

2023-08-17 08:24 UTC, tamasm-wg commented
Is there any reason you are using .js files? Every file (models, controllers, services, etc. ) should be typescript files.

2023-08-23 05:57 UTC, closed without merging